apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgBfpA2sOjycN7x2jc2z17rpS9DQlBeTay4hSiXuTHkXbBfzNxvXdYyNlhk01OB93MNvPAgX8teAtaDrdstTT/BIUB7BOTR7mP1lKSMHzojOn5Cw8zbmH94rwJ+Sjun4rPOMFfCrcbr71xNjtcuK6Gz74gyyZ8YtZsf2ueX5+0xfY8PM1nRiXrApZt7VJm3H9uVlFwSoAyJUj0XOIxWjF2VMb5Himplnaae1oTboZgqPovKrbzrWNMQqQUbTkA8LveV+HbetsugAF6wGrMuImj912oU0I4UyPa/gXDbqKIVdqPFNujJECve1zx2Sne8JfyJt9x3KXNmAnxPmXNjnQ5x3G2FzmXpR4lddr3D9oK5TqQvBYg75FOQklmF8PgR661XykgvY/VN6rJVgyjTXecpKyNNWZZ9RpAgfaN7YvyZhdXaM9jP7/n2yNC/jtmumV7NYg5vyZNjh8i6E+lOdztBcnZwaX3Cg1a79RFulJLxDHeq6+mGe2BnZqUJZg3g4ZczD5tkU0MBUVjfWVWuT91agiyPDSURswolTRM2Hzc3X2QY808/QNYFF64GvPh9ooMQOGnIjU4wtmm8WVTm2KORtamWOuTvgRs/0G27v/IcqrBSHPioL5PwaVRiHcZ9yMdjlGqOPMoJiKUKHKN/ev0Cr65P4cheotg5dnv7FT/5APeerVEYBq21begaGMSwtNYm/g2CSQrduBGDW/XYXcH4GSMmWkj9M3a0YoAoPPGcQiJBL7TD0jbrYntPOXkAeVva5GktGzuOEE6ffMTiSNeflzaPOJPbjCu5sSwxT5X3o9TL/gkjjSQaVgIqbG7B6AkNXieN5TCQv4nMZYHR1fHmykV9jCDVuVn//rnZpT1+41ESkwhbkTUoZjf7ezQAQH8XAPRU+rcPOCS2lnFv7r/Go7TvC0HAhvcbHmPeyt+Qi5EJmJ/iLzvhxVnjGxbQR0zG4KuqBll8KxU4wvLiRWpeVjnc88w1QpCBcwDH/8h/ldpIeGilGcAGTRkitVcLns3g5KAOUc376tXtJwxqCSJbrXRnmA/6f5cG+Rd/Lopk1LwMgzDWOVApUGCB0D4Voyim2Q9r5Y330etBgT1kb+p00dTw4LjooSVk5K703uAvLpoFcx7SZX38yuRxmKn7QWEkBueibSLe8WU0g+mAiygSpo5CJpwolnkRYIOWIl33gJgXYsCWBhbt5jJCEIufbGN5MztY3y70kwPP0FgrG7JAd47YjWWkuR2wFalgYuQNzoHWolvrpAu77mVw0mmi4xrjgmQHuZNZ4ZFgaoKf2eV9GqVTHQyCXMgM5EkKaYRTYXW7K5hbWyjbgeb0QvclNO9z2
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

